parameters:
    sam.permissions:
        BUSINESS_VIEW_USER:
            label: perm.show.user_label
            description: perm.show.user_desc
        BUSINESS_MANAGE_USER:
            label: perm.manage.user_label
            description: perm.manage.user_desc
        BUSINESS_MANAGE_USER_PERIMETER:
            label: perm.manage.perimeter_label
            description: perm.manage.perimeter_desc
        BUSINESS_MANAGE_PERMISSION:
            label: perm.manage.perm_role_label
            description: perm.manage.perm_role_desc
        BUSINESS_VIEW_ROLE:
            label: perm.show.role_label
            description: perm.show.role_desc
        BUSINESS_MANAGE_ROLE:
            label: perm.manage.role_label
            description: perm.manage.role_desc
        BUSINESS_CREATE_SUPER_ADMIN:
            label: perm.godlike.user_label
            description:  perm.godlike.user_desc
        BUSINESS_MANAGE_CLIENT:
            label: perm.manage.customer_label
            description: perm.manage.customer_desc
        BUSINESS_CREATE_CLIENT:
            label: perm.create.customer_label
            description: perm.create.customer_desc
