canal_tp_sam_homepage:
    path:  /
    defaults: { _controller: CanalTPSamCoreBundle:Sam:index }

sam_customer_list:
    path:  /customer
    defaults: { _controller: CanalTPSamCoreBundle:Customer:list }

sam_customer_new:
    path:  /customer/new
    defaults: { _controller: CanalTPSamCoreBundle:Customer:new }

sam_customer_edit:
    path:  /customer/{id}/edit
    defaults: { _controller: CanalTPSamCoreBundle:Customer:edit }

canal_tp_sam_network_list_json:
    path: /coverage/{externalCoverageId}/networks
    defaults: { _controller: CanalTPSamCoreBundle:Customer:byCoverage }
    options:
        expose: true

canal_tp_sam_network_check_permission_json:
    path: /coverage/{externalCoverageId}/networks/{externalNetworkId}/{token}
    defaults: { _controller: CanalTPSamCoreBundle:Customer:checkAllowedToNetwork }
    requirements:
        token: -?[a-zA-Z0-9_\-:]*
    options:
        expose: true
        
sam_customer_regeneratetoken:
    path:  /customer/{id}/token/{appId}/regenerate
    defaults: { _controller: CanalTPSamCoreBundle:Customer:regenerateToken }

sam_customer_regeneratealltokens:
    path:  /customer/{id}/tokens/regenerate
    defaults: { _controller: CanalTPSamCoreBundle:Customer:regenerateTokens }

sam_customer_listtokens:
    path:  /customer/{id}/tokens
    defaults: { _controller: CanalTPSamCoreBundle:Customer:listTokens }