<?php

namespace CanalTP\SamCoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRoleRepository extends EntityRepository
{
    /**
     * Return roles with parent
     * @return type
     */
    public function findAllWithParent() {
        return $this->createQueryBuilder('a')
                    ->join('a.role', 'p')
                    ->getQuery()
                    ->getResult();
    }

    /**
     * Return roles for applications
     */
    public function findAllByApplications($applications) {

        return $this->_em->createQuery('SELECT r FROM CanalTPSamCoreBundle:ApplicationRole r LEFT JOIN r.application a WHERE a IN (:application) ORDER BY a.id')
             ->setParameter('application', $applications)
             ->getResult();
    }

    /**
     * Find rolesByApplicationId
     */
    public function findRolesBy($user_id, $name)
    {
        return $this->createQueryBuilder('a')
                    ->join('a.users', 'p')
                    ->where('p.id = :user_id')
                    ->join('a.application', 'app')
                    ->andWhere('app.canonicalName = :name')
                    ->setParameter('name', $name)
                    ->setParameter('user_id', $user_id)
                    ->getQuery()
                    ->getResult();
    }
}
