<?php

namespace CanalTP\IussaadCoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends EntityRepository
{    
    /**
     * Retourne tous les applications en base de données
     * @param type $user
     * @return type
     */
    public function findAllByUser($user)
    {
        return $this->createQueryBuilder('a')
                ->getQuery()
                ->getResult();
    }
}
