<?php

namespace CanalTP\SamCoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository
{
    public function findAllToArray()
    {
        $customers = array();

        foreach ($this->findAll() as $customer) {
            $customers[$customer->getId()] = $customer->getName();
        }
        return ($customers);
    }

    public function findByToArray($criterias)
    {
        $customers = array();

        foreach ($this->findBy($criterias) as $customer) {
            $customers[$customer->getId()] = $customer->getName();
        }
        return ($customers);
    }
}
