<?php

namespace CanalTP\SamCoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
    /**
     * Return roles with parent
     * @return type
     */
    public function findAllWithParent() {
        return $this->createQueryBuilder('a')
                    ->join('a.applicationRoles', 'p')
                    ->getQuery()
                    ->getResult();
    }
        
    public function findByRoleJoinedToRequestMatcher(Array $roles) {
        $roles = $this->findByRole($roles);
        $result = array();
        foreach($roles as $role)
        {
            foreach ($role->getRequestMatchers() as $requestMatcher)
            {
                if ($requestMatcher->isDomainComponent())
                {
                    $result[] = $requestMatcher;
                }
            }
        }
        return $result;
    }    
}
