<?php

namespace CanalTP\IussaadCoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SimRepository extends EntityRepository
{
}
